name: build-and-test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup C++ and CMake
        uses: aminya/setup-cpp@v0.34.0
        with:
          compiler: llvm
          llvm-version: "15"
          cmake: true
          ninja: true

      - name: Configure
        run: cmake -B build -DCMAKE_CXX_STANDARD=23 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure
